export const demoPunishments = [
  "Take 2 shots of your drink",
  "Do 10 push-ups or take a shot",
  "Sing a song chosen by the group",
  "Let someone draw on your face with a marker",
  "Swap drinks with another player for the next round",
  "Dance for 30 seconds without music",
  "Text your ex or take 2 shots",
  "Wear a silly hat for the next 3 rounds",
  "Speak in an accent until your next turn",
  "Do a truth or dare chosen by the group",
  "Give a compliment to every player",
  "Act like an animal for 1 minute",
  "Let another player post a status on your social media",
  "Do a dramatic reading of a text message on your phone",
  "Pretend to be a waiter and take everyone’s drink orders",
  "Hold an ice cube in your hand until it melts",
  "Let someone else choose your next drink",
  "Switch seats with the person to your left",
  "Do your best impression of another player",
  "Give a 1-minute speech on a random topic chosen by the group",
];

export const demoPunishments_wpl = [
  "Take 2 shots and send a selfie to {{player}}",
  "Do 10 push-ups or take a shot and dedicate it to {{player}}",
  "Sing a song chosen by {{player}}",
  "Let {{player}} draw on your face with a marker",
  "Swap drinks with {{player}} for the next round",
  "Dance for 30 seconds while {{player}} watches",
  "Text {{player}} something nice or take 2 shots",
  "Wear a silly hat chosen by {{player}} for the next 3 rounds",
  "Speak in an accent of {{player}}'s choice until your next turn",
  "Do a truth or dare chosen by {{player}}",
  "Give {{player}} a compliment and take a drink",
  "Act like {{player}} for 1 minute",
  "Let {{player}} post a status on your social media",
  "Do a dramatic reading of a text message from {{player}}",
  "Pretend to be {{player}}'s personal assistant for 1 minute",
  "Hold an ice cube in your hand until it melts while {{player}} watches",
  "Let {{player}} choose your next drink",
  "Switch seats with {{player}} for the next 2 rounds",
  "Do your best impression of {{player}}",
  "Give a 1-minute speech about {{player}}'s most interesting trait",
];
