export const demoQuestions = [
  "Who is most likely to win a Nobel Prize?",
  "Who is most likely to become a famous actor?",
  "Who is most likely to go skydiving?",
  "Who is most likely to get lost in their own neighborhood?",
  "Who is most likely to start a new trend?",
  "Who is most likely to accidentally send a text to the wrong person?",
  "Who is most likely to survive a zombie apocalypse?",
  "Who is most likely to forget someone's birthday?",
  "Who is most likely to adopt a stray animal?",
  "Who is most likely to binge-watch an entire TV series in one day?",
  "Who is most likely to break a world record?",
  "Who is most likely to eat dessert before dinner?",
  "Who is most likely to run a marathon?",
  "Who is most likely to be late to their own wedding?",
  "Who is most likely to become a millionaire?",
  "Who is most likely to pull an all-nighter?",
  "Who is most likely to become a stand-up comedian?",
  "Who is most likely to go on a spontaneous road trip?",
  "Who is most likely to be the last one dancing at a party?",
  "Who is most likely to forget where they parked their car?",
];

export const demoQuestions_wpl = [
  "Who is most likely to marry {{player}}?",
  "Who is most likely to go on a road trip with {{player}}?",
  "Who is most likely to prank {{player}}?",
  "Who is most likely to embarrass {{player}} in public?",
  "Who is most likely to start a business with {{player}}?",
  "Who is most likely to tell a secret to {{player}}?",
  "Who is most likely to take care of {{player}} when they’re drunk?",
  "Who is most likely to give {{player}} the best advice?",
  "Who is most likely to travel the world with {{player}}?",
  "Who is most likely to sing a duet with {{player}}?",
  "Who is most likely to have a crush on {{player}}?",
  "Who is most likely to share a deep secret with {{player}}?",
  "Who is most likely to team up with {{player}} in a competition?",
  "Who is most likely to trust {{player}} with their life?",
  "Who is most likely to get into trouble because of {{player}}?",
  "Who is most likely to move in with {{player}}?",
  "Who is most likely to plan a surprise party for {{player}}?",
  "Who is most likely to share a winning lottery ticket with {{player}}?",
  "Who is most likely to forget {{player}}'s birthday?",
  "Who is most likely to take a bullet for {{player}}?",
];
